### ISSUE TITLE
Fix Offline backup AWS/Openstack/Azure

### ISSUE THREAD

**Issue by kamath-prasad** [cloudfoundry-incubator/service-fabrik-blueprint-service#8]
The offline backup is broken for AWS / Openstack / Azure . Need to fix the same.

**Comment by sauravmndl-zz** [comment]
The OpenStack offline backup was okay. But in case of AWS it was a bug I assume, as in case of AWS it was taking both snapshot and tarball for same backup guid. But refactored the whole code and tested in Azure. It is working fine.
